export const WALLET_TYPES = {
    EXECUTE_CONTRACT: "EXECUTE_CONTRACT",
    WALLET_SIGN_REQUEST: "WALLET_SIGN_REQUEST",
    WALLET_SIGN_RESPONSE: "WALLET_SIGN_RESPONSE",
    WALLET_ARBITRARY_REQUEST: "WALLET_ARBITRARY_REQUEST",
    WALLET_ARBITRARY_RESPONSE: "WALLET_ARBITRARY_RESPONSE",
    INITIATE_CONTRACT: "INITIATE_CONTRACT",
    DEPLOY_NFT: "DEPLOY_NFT",
    INITIATE_DEPLOY_NFT: "INITIATE_DEPLOY_NFT",
    EXECUTE_NFT: "EXECUTE_NFT",
    INITIATE_EXECUTE_NFT: "INITIATE_EXECUTE_NFT",
    TRANSFER_FT: "TRANSFER_FT",
    INITIATE_TRANSFER_FT: "INITIATE_TRANSFER_FT",
    EXECUTE_FT: "EXECUTE_FT",
    STORE_USER_DETAILS: "STORE_USER_DETAILS",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    CLEAR_USER_DETAILS: "CLEAR_USER_DETAILS",
    CREATE_FT: "CREATE_FT",
    INITIATE_CREATE_FT: "INITIATE_CREATE_FT",
}
export const ENUMS = {
    INITIAL_ACTIVE_TIME: "INITIAL_ACTIVE_TIME"
}